#!/usr/bin/env bash
# Sets up Nginx server with an html file

# run update and install nginx
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get install -y nginx

# change firewall to allow nginx
sudo ufw allow 'Nginx HTTP'

# echo 'Hello World' into html file
sudo sh -c 'echo "Hello World" > /var/www/html/index.html'

# start the nginx service
sudo service nginx start
