#!/usr/bin/env bash
# Sets up Nginx server with an html file & redirect & 404 page

# run update and install nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# change firewall to allow nginx
sudo ufw allow 'Nginx HTTP'

# echo 'Hello World' into html file
sudo sh -c 'echo "Hello World" > /var/www/html/index.html'

# start the nginx service
sudo service nginx start

# find location in the config file and update 301 redirect
findloc="^\tlocation / {"
update301="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://dndbeyond.com;\n\t}\n\n\tlocation / {"
sudo sed -i "s@$findloc@$update301@" /etc/nginx/sites-available/default

# update the 404 error
update404="\terror_page 404 /error404.html;\n\n\tlocation / {"
sudo sed -i "s@$findloc@$update404@" /etc/nginx/sites-available/default

# restart the nginx service
sudo service nginx restart
