#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely, and displays "I am invincible!!!" when receiving a SIGTERM signal.

BUZZ="1"

while [ $BUZZ != 0 ]
      do
	echo "To infinity and beyond"

	sleep 2
	
	trap 'echo I am invincible!!!' SIGTERM

done

