#!/usr/bin/env bash
# This script displays the numbers from 1 to 100. If the number is a multiple of both 3 and 5, then it displays "FizzBuzz" instead of the number. If the number is a multiple of 3, then it displays "Fizz" instead of the number. If the number is a multple of 5, then it displays "Buzz" instead of the number.

NUM="1"

while [ $NUM -le 100 ]
do  
	  if [[ $((NUM%3)) = 0 && $((NUM%5)) = 0 ]]; then
	     echo "FizzBuzz"
	  
	  elif [[ $((NUM%3)) = 0 && $((NUM%5)) != 0 ]]; then
	     echo "Fizz"
	      
       	  elif [[ $((NUM%3)) != 0 && $((NUM%5)) = 0 ]]; then 
	     echo "Buzz"
	  else
	     echo "$NUM"

	  fi
	      	  
	  NUM=$((NUM+1))
done
