#!/usr/bin/env bash
# This script displays the numbers from 1 to 100. If the number is a multiple of both 3 and 5, then it displays "FizzBuzz" instead of the number. If the number is a multiple of 3, then it displays "Fizz" instead of the number. If the number is a multple of 5, then it displays "Buzz" instead of the number.

NUM="1"
DIV3=$(($NUM%3))
DIV5=$(($NUM%5))

while [ $NUM -le 100 ]
do  
	  if [[ $DIV3 -eq 0 && $DIV5 -eq 0 ]]; then
	     echo "FizzBuzz"
	  
	  elif [[ $DIV3 -eq 0 && $DIV5 -ne 0 ]]; then
	     echo "Fizz"
	      
       	  elif [[ $DIV3 -ne 0 && $DIV5 -eq 0 ]]; then 
	     echo "Buzz"
	  else
	     echo "$NUM"

	  fi
	      	  
      NUM=$[ $NUM + 1 ]
done
