#!/usr/bin/env bash
# This script displays "Holberton School" 10 times, except on the 4th and 8th iteration where it displays "bad luck" an#+ d "good luck", respectively.

x="1"

while [ $x -le 10 ]

do
    if [ $x -eq 4 ]; then
	echo "bad luck"

    elif [ $x -eq 8 ]; then
	 echo "good luck"

    else
	echo "Holberton School"

    fi

    x=$((x + 1))
	 
done
