#!/usr/bin/env bash
# This script displays numbers 1 to 20. On the 4th iteration it also displays "bad luck from China" on a new line. On t#+ he 9th iteration it also displays "bad luck from Japan" on a new line. On the 17th iteration it also displays "bad l#+ uck from Italy" on a new line.

x="1"

while [ $x -le 20 ]

do

	echo "$x"

	case $x in
	4)
		echo "bad luck from China"
		;;

	9)
		echo "bad luck from Japan"
		;;

	17)
		echo "bad luck from Italy"
		;;
	esac

	x=$(( $x + 1 ))
done
