#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

HOUR="0"

while [ $HOUR -le 12 ]; do

    echo "Hour: $HOUR"

    printf '%s\n' {1..59}
    
    HOUR=$((HOUR+1))

done
