#!/usr/bin/env bash
# This script lists the contents of the current directory without the information in the file names before the first "-" character.

for i in *;
do

    echo "$i" | cut -d '-' -f2-

done
