#!/usr/bin/env bash
# This script gives you information about the "holbertonschool" file. Namely, if it exists, and if it does whethertit is empty, not empty, and if it is a regular file.

if [ -e holbertonschool ]
   then
       echo "holbertonschool file exists"
       if [ -s holbertonschool ]
       then
	   echo "holbertonschool file is not empty"
       else
	   echo "holbertonschool file is empty"
       fi
	   if [ -f holbertonschool ]
	   then
	       echo "holbertonschool file is a regular file"
	   fi
       
   else
       echo "holbertonschool file does not exist"
fi
